Repository googleapis/google-http-java-client, pull requests merged in 2019-08, with the labels that each got.

#760 Update guava
  pom.xml
Labels: cla: yes

#759 Update URL
  .gitignore
  google-http-client/src/main/java/com/google/api/client/json/webtoken/JsonWebSignature.java
  google-http-client/src/main/java/com/google/api/client/json/webtoken/JsonWebToken.java
  samples/dailymotion-simple-cmdline-sample/.classpath
  samples/dailymotion-simple-cmdline-sample/.project
Labels: cla: yes

#763 remove deprecated code, fix warnings, and use JUnit 4
  google-http-client-apache-v2/src/main/java/com/google/api/client/http/apache/v2/ApacheHttpTransport.java
  google-http-client-apache-v2/src/main/java/com/google/api/client/http/apache/v2/package-info.java
  google-http-client-test/src/main/java/com/google/api/client/test/json/AbstractJsonGeneratorTest.java
  google-http-client-test/src/main/java/com/google/api/client/test/json/AbstractJsonParserTest.java
  google-http-client/src/main/java/com/google/api/client/http/javanet/NetHttpTransport.java
  google-http-client/src/main/java/com/google/api/client/util/FieldInfo.java
  google-http-client/src/test/java/com/google/api/client/http/HttpRequestTest.java
  google-http-client/src/test/java/com/google/api/client/util/GenericDataTest.java
Labels: cla: yes

#767 stop exposing internal private state
  google-http-client/src/main/java/com/google/api/client/json/webtoken/JsonWebSignature.java
  google-http-client/src/test/java/com/google/api/client/json/webtoken/JsonWebSignatureTest.java
Labels: cla: yes

#775 Remove google-http-client-jdo
  versions.txt
Labels: cla: yes

#773 remove maven jarjar plugin
  pom.xml
Labels: cla: yes

#783 add module name to submodules
  google-http-client-android/pom.xml
  google-http-client-appengine/pom.xml
  google-http-client-findbugs/pom.xml
  google-http-client-gson/pom.xml
  google-http-client-jackson2/pom.xml
  google-http-client-protobuf/pom.xml
  google-http-client-xml/pom.xml
  samples/dailymotion-simple-cmdline-sample/.settings/org.eclipse.jdt.core.prefs
Labels: cla: yes

#777 Remove deprecated testing method
  clirr-ignored-differences.xml
  google-http-client/src/main/java/com/google/api/client/testing/http/MockHttpTransport.java
Labels: cla: yes, semver: minor

#785 remove obsolete and deprecated parent
  pom.xml
Labels: cla: yes, semver: patch

#769 remove deprecated methods
  clirr-ignored-differences.xml
  google-http-client/src/main/java/com/google/api/client/json/webtoken/JsonWebSignature.java
Labels: cla: yes, semver: minor

#786 Import google_checks.xml for maven-checkstyle-plugin
  checkstyle.xml
  pom.xml
  samples/checkstyle.xml
  samples/dailymotion-simple-cmdline-sample/pom.xml
Labels: cla: yes

#766 Update to protobuf 3.9.1
  pom.xml
Labels: cla: yes, semver: patch

#765 Point README developer guide and setup instructions to the GitHub wiki
  README.md
Labels: cla: yes

#787 Regenerate common configuration files from our templates
  .kokoro/common.cfg
  .kokoro/continuous/common.cfg
  .kokoro/continuous/dependencies.cfg
  .kokoro/continuous/integration.cfg
  .kokoro/continuous/java11.cfg
  .kokoro/continuous/java7.cfg
  .kokoro/continuous/java8.cfg
  .kokoro/continuous/lint.cfg
  .kokoro/nightly/common.cfg
  .kokoro/nightly/dependencies.cfg
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/java11.cfg
  .kokoro/nightly/java7.cfg
  .kokoro/nightly/java8.cfg
  .kokoro/nightly/lint.cfg
  .kokoro/presubmit/common.cfg
  .kokoro/presubmit/dependencies.cfg
  .kokoro/presubmit/integration.cfg
  .kokoro/presubmit/java11.cfg
  .kokoro/presubmit/java7.cfg
  .kokoro/presubmit/java8.cfg
  .kokoro/presubmit/linkage-monitor.cfg
  .kokoro/presubmit/lint.cfg
  .kokoro/release/common.cfg
  .kokoro/release/drop.cfg
  .kokoro/release/promote.cfg
  .kokoro/release/snapshot.cfg
  .kokoro/release/stage.cfg
  synth.metadata
Labels: cla: yes

#792 build: fix missing version warnings
  google-http-client-bom/pom.xml
Labels: cla: yes

#798 Regenerate common configuration from templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  synth.metadata
Labels: cla: yes

#804 fix: disable uri normalization in ApacheHttpRequest
  google-http-client-apache-v2/src/main/java/com/google/api/client/http/apache/v2/ApacheHttpRequest.java
  google-http-client-apache-v2/src/test/java/com/google/api/client/http/apache/v2/ApacheHttpTransportTest.java
Labels: cla: yes
