Repository googleapis/google-http-java-client, pull requests merged in 2019-07, with the labels that each got.

#722 Release google-http-java-client v1.30.2
  google-http-client-android-test/pom.xml
  google-http-client-android/pom.xml
  google-http-client-apache-v2/pom.xml
  google-http-client-appengine/pom.xml
  google-http-client-assembly/pom.xml
  google-http-client-bom/README.md
  google-http-client-bom/pom.xml
  google-http-client-findbugs/pom.xml
  google-http-client-gson/pom.xml
  google-http-client-jackson2/pom.xml
  google-http-client-protobuf/pom.xml
  google-http-client-test/pom.xml
  google-http-client-xml/pom.xml
  google-http-client/pom.xml
  pom.xml
  samples/dailymotion-simple-cmdline-sample/pom.xml
  versions.txt
Labels: :rotating_light:, autorelease: pending, cla: yes

#721 Add GitHub repo, issue tracker metadata for javadoc site
  .kokoro/release/publish_javadoc.sh
Labels: :rotating_light:, cla: yes

#738 Adds CI test for mvn dependency:analyze and fixes missing deps
  .kokoro/dependencies.sh
  .kokoro/presubmit/dependencies.cfg
  google-http-client-apache-v2/pom.xml
  google-http-client-appengine/pom.xml
  google-http-client-findbugs/pom.xml
  google-http-client-gson/pom.xml
  google-http-client-jackson2/pom.xml
  google-http-client/pom.xml
  pom.xml
Labels: cla: yes

#751 new ClassName().getClass() -> ClassName.class
  google-http-client/src/test/java/com/google/api/client/util/DataTest.java
  google-http-client/src/test/java/com/google/api/client/util/TypesTest.java
Labels: cla: yes

#752 Add support for nanosecond precision when parsing rfc3339 strings
  google-http-client/src/main/java/com/google/api/client/util/DateTime.java
  google-http-client/src/test/java/com/google/api/client/util/DateTimeTest.java
Labels: cla: yes, semver: minor

#754 Release google-http-java-client v1.31.0
  google-http-client-android-test/pom.xml
  google-http-client-android/pom.xml
  google-http-client-apache-v2/pom.xml
  google-http-client-appengine/pom.xml
  google-http-client-assembly/pom.xml
  google-http-client-bom/README.md
  google-http-client-bom/pom.xml
  google-http-client-findbugs/pom.xml
  google-http-client-gson/pom.xml
  google-http-client-jackson2/pom.xml
  google-http-client-protobuf/pom.xml
  google-http-client-test/pom.xml
  google-http-client-xml/pom.xml
  google-http-client/pom.xml
  pom.xml
  samples/dailymotion-simple-cmdline-sample/pom.xml
  versions.txt
Labels: autorelease: pending, cla: yes

#755 Bump next snapshot
  google-http-client-android-test/pom.xml
  google-http-client-android/pom.xml
  google-http-client-apache-v2/pom.xml
  google-http-client-appengine/pom.xml
  google-http-client-assembly/pom.xml
  google-http-client-bom/pom.xml
  google-http-client-findbugs/pom.xml
  google-http-client-gson/pom.xml
  google-http-client-jackson2/pom.xml
  google-http-client-protobuf/pom.xml
  google-http-client-test/pom.xml
  google-http-client-xml/pom.xml
  google-http-client/pom.xml
  pom.xml
  samples/dailymotion-simple-cmdline-sample/pom.xml
  versions.txt
Labels: cla: yes
