Repository googleapis/google-http-java-client, pull requests merged in 2019-05, with the labels that each got.

#635 Add 404 redirect to new javadoc site
  .gitignore
  404.html
  package.json
  src/redirects.js
  test/redirects.js
Labels: :rotating_light:, cla: yes

#636 Update links to javadoc to point to googleapis.dev
  README.md
Labels: cla: yes

#639 Fix deadlock caused by concurrent class loading
  google-http-client/src/main/java/com/google/api/client/util/Data.java
Labels: cla: yes

#643 Remove blocking ClassInfo.of
  google-http-client/src/main/java/com/google/api/client/util/ClassInfo.java
Labels: cla: yes

#641 Restore the ApacheHttpRequest implementation.
  google-http-client/src/main/java/com/google/api/client/http/apache/ApacheHttpRequest.java
Labels: cla: yes, release blocking

#640 Fix a bunch of typos
  google-http-client-xml/src/main/java/com/google/api/client/xml/Xml.java
  google-http-client-xml/src/main/java/com/google/api/client/xml/XmlNamespaceDictionary.java
  google-http-client/src/main/java/com/google/api/client/http/HttpEncoding.java
  google-http-client/src/main/java/com/google/api/client/http/javanet/NetHttpRequest.java
  google-http-client/src/main/java/com/google/api/client/util/Key.java
  google-http-client/src/main/java/com/google/api/client/util/StreamingContent.java
  google-http-client/src/main/java/com/google/api/client/util/StringUtils.java
Labels: cla: yes

#645 Linting cleanup
  google-http-client/src/main/java/com/google/api/client/http/HttpHeaders.java
  google-http-client/src/main/java/com/google/api/client/util/Objects.java
Labels: cla: yes

#647 Remove deprecated google-http-client-jackson artifact.
  google-http-client-assembly/assembly.xml
  google-http-client-assembly/pom.xml
  google-http-client-assembly/properties/google-http-client-jackson.jar.properties
  google-http-client-assembly/properties/jackson-core-asl.jar.properties
  google-http-client-bom/pom.xml
  google-http-client-jackson/pom.xml
  google-http-client-jackson/src/main/java/com/google/api/client/json/jackson/JacksonFactory.java
  google-http-client-jackson/src/main/java/com/google/api/client/json/jackson/JacksonGenerator.java
  google-http-client-jackson/src/main/java/com/google/api/client/json/jackson/JacksonParser.java
  google-http-client-jackson/src/main/java/com/google/api/client/json/jackson/package-info.java
  google-http-client-jackson/src/test/java/com/google/api/client/json/jackson/JacksonFactoryTest.java
  google-http-client-jackson/src/test/java/com/google/api/client/json/jackson/JacksonGeneratorTest.java
  pom.xml
  versions.txt
Labels: cla: yes

#644 Add Base64Test case for some base64 decoding edge cases
  google-http-client/src/main/java/com/google/api/client/util/Base64.java
  google-http-client/src/test/java/com/google/api/client/util/Base64Test.java
Labels: cla: yes
