Repository googleapis/google-http-java-client, pull requests merged in 2019-02, with the labels that each got.

#580 Upgrade surefire plugin to fix the build
  pom.xml
Labels: :rotating_light:, cla: yes

#577 Update README.md with Java 7 support
  README.md
Labels: :rotating_light:, cla: yes

#572 Fix handling interrupted uploads
  google-http-client/src/main/java/com/google/api/client/http/javanet/NetHttpRequest.java
  google-http-client/src/test/java/com/google/api/client/http/javanet/NetHttpRequestTest.java
Labels: :rotating_light:, cla: yes

#565 Cleanup assembly process.
  google-http-client-assembly/assembly.xml
  google-http-client-assembly/dependencies/css/maven-base.css
  google-http-client-assembly/dependencies/css/maven-theme.css
  google-http-client-assembly/dependencies/css/print.css
  google-http-client-assembly/dependencies/css/site.css
  google-http-client-assembly/dependencies/google-http-client-android-dependencies.html
  google-http-client-assembly/dependencies/google-http-client-appengine-dependencies.html
  google-http-client-assembly/dependencies/google-http-client-dependencies.html
  google-http-client-assembly/dependencies/google-http-client-gson-dependencies.html
  google-http-client-assembly/dependencies/google-http-client-jackson-dependencies.html
  google-http-client-assembly/dependencies/google-http-client-jackson2-dependencies.html
  google-http-client-assembly/dependencies/google-http-client-jdo-dependencies.html
  google-http-client-assembly/dependencies/google-http-client-protobuf-dependencies.html
  google-http-client-assembly/dependencies/google-http-client-xml-dependencies.html
  google-http-client-assembly/dependencies/images/close.gif
  google-http-client-assembly/dependencies/images/collapsed.gif
  google-http-client-assembly/dependencies/images/expanded.gif
  google-http-client-assembly/dependencies/images/external.png
  google-http-client-assembly/dependencies/images/icon_error_sml.gif
  google-http-client-assembly/dependencies/images/icon_info_sml.gif
  google-http-client-assembly/dependencies/images/icon_success_sml.gif
  google-http-client-assembly/dependencies/images/icon_warning_sml.gif
  google-http-client-assembly/dependencies/images/logos/build-by-maven-black.png
  google-http-client-assembly/dependencies/images/logos/build-by-maven-white.png
  google-http-client-assembly/dependencies/images/logos/maven-feather.png
  google-http-client-assembly/dependencies/images/newwindow.png
  google-http-client-assembly/licenses/APACHE-LICENSE.txt
  google-http-client-assembly/licenses/BSD-LICENSE.txt
  google-http-client-assembly/licenses/CDDL-LICENSE.txt
  google-http-client-assembly/licenses/xpp3_LICENSE.txt
  google-http-client-assembly/pom.xml
  google-http-client-assembly/properties/google-http-client-apache.jar.properties
  google-http-client-assembly/properties/gson.jar.properties
  google-http-client-assembly/properties/jackson-core-asl.jar.properties
  google-http-client-assembly/properties/jackson-core.jar.properties
  google-http-client-assembly/properties/protobuf-java.jar.properties
  pom.xml
Labels: :rotating_light:, cla: yes

#579 Add option to return raw stream from response
  google-http-client/src/main/java/com/google/api/client/http/HttpRequest.java
  google-http-client/src/main/java/com/google/api/client/http/HttpResponse.java
  google-http-client/src/test/java/com/google/api/client/http/HttpResponseTest.java
Labels: :rotating_light:, cla: yes

#480 remove datanucleus
  google-http-client-jdo/pom.xml
  pom.xml
Labels: :rotating_light:, cla: yes, do not merge

#587 ignore Mac Finder metadata
  .gitignore
Labels: cla: yes

#588 372: Changed SingleThreadExecutor to FixedThreadPool(1).
  google-http-client/src/main/java/com/google/api/client/http/HttpRequest.java
Labels: cla: yes

#590 Update comment to match plugin configuration
  google-http-client-appengine/pom.xml
Labels: cla: yes

#589 Implement equals and Hashcode on GenericData
  google-http-client/src/main/java/com/google/api/client/util/GenericData.java
  google-http-client/src/test/java/com/google/api/client/json/GenericJsonTest.java
  google-http-client/src/test/java/com/google/api/client/util/GenericDataTest.java
Labels: cla: yes

#584 Remove old JDO artifact
  google-http-client-assembly/assembly.xml
  google-http-client-assembly/classpath-include
  google-http-client-assembly/pom.xml
  google-http-client-assembly/properties/google-http-client-jdo.jar.properties
  google-http-client-assembly/readme.html
  google-http-client-jdo/pom.xml
  google-http-client-jdo/src/main/java/com/google/api/client/extensions/jdo/JdoDataStoreFactory.java
  google-http-client-jdo/src/main/java/com/google/api/client/extensions/jdo/package-info.java
  google-http-client-jdo/src/test/java/com/google/api/client/extensions/jdo/JdoDataStoreFactoryTest.java
  pom.xml
Labels: cla: yes

#594 remove duplicate version definition
  pom.xml
Labels: cla: yes

#592 more fixes for Java 7 minimum version
  google-http-client-apache-legacy/pom.xml
  google-http-client-apache/pom.xml
  google-http-client/pom.xml
  samples/dailymotion-simple-cmdline-sample/instructions.html
Labels: cla: yes

#596 upgrade dependencies
  pom.xml
Labels: cla: yes

#591 depend directly on Apache httpclient
  google-http-client/pom.xml
Labels: cla: yes, kokoro:force-run

#598 update instructions
  samples/dailymotion-simple-cmdline-sample/instructions.html
Labels: cla: yes

#600 remove Java 5 reference
  google-http-client-assembly/readme.html
Labels: cla: yes

#602 Added unit tests for null enum and unknown enum.
  google-http-client/src/test/java/com/google/api/client/util/DataTest.java
Labels: cla: yes

#605 Release google-http-java-client v1.29.0
  google-http-client-android-test/pom.xml
  google-http-client-android/pom.xml
  google-http-client-apache-legacy/pom.xml
  google-http-client-apache/pom.xml
  google-http-client-appengine/pom.xml
  google-http-client-assembly/pom.xml
  google-http-client-bom/README.md
  google-http-client-bom/pom.xml
  google-http-client-findbugs/pom.xml
  google-http-client-gson/pom.xml
  google-http-client-jackson/pom.xml
  google-http-client-jackson2/pom.xml
  google-http-client-protobuf/pom.xml
  google-http-client-test/pom.xml
  google-http-client-xml/pom.xml
  google-http-client/pom.xml
  pom.xml
  samples/dailymotion-simple-cmdline-sample/pom.xml
  versions.txt
Labels: cla: yes

#607 Revert "Release google-http-java-client v1.29.0"
  google-http-client-android-test/pom.xml
  google-http-client-android/pom.xml
  google-http-client-apache-legacy/pom.xml
  google-http-client-apache/pom.xml
  google-http-client-appengine/pom.xml
  google-http-client-assembly/pom.xml
  google-http-client-bom/README.md
  google-http-client-bom/pom.xml
  google-http-client-findbugs/pom.xml
  google-http-client-gson/pom.xml
  google-http-client-jackson/pom.xml
  google-http-client-jackson2/pom.xml
  google-http-client-protobuf/pom.xml
  google-http-client-test/pom.xml
  google-http-client-xml/pom.xml
  google-http-client/pom.xml
  pom.xml
  samples/dailymotion-simple-cmdline-sample/pom.xml
  versions.txt
Labels: cla: yes

#601 Added Warning header and unit tests.
  google-http-client/src/main/java/com/google/api/client/http/HttpHeaders.java
  google-http-client/src/test/java/com/google/api/client/http/HttpHeadersTest.java
Labels: :rotating_light:, cla: yes
