Repository googleapis/google-http-java-client, pull requests merged in 2020-11, with the labels that each got.

#1170 chore: libraries-bom 13.4.0
  docs/setup.md
Labels: cla: yes

#1168 feat: add isMtls property to ApacheHttpTransport
  google-http-client-apache-v2/src/main/java/com/google/api/client/http/apache/v2/ApacheHttpTransport.java
  google-http-client-apache-v2/src/test/java/com/google/api/client/http/apache/v2/ApacheHttpTransportTest.java
Labels: cla: yes

#1163 chore: remove TravisCI config
  .travis.yml
Labels: cla: yes

#1175 chore(java): use production staging bucket
  .kokoro/release/publish_javadoc.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full

#1177 docs: BOM 15.0.0
  docs/setup.md
Labels: cla: yes

#1179 chore(java): ignore return code 28 in README autosynth job
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#1181 chore: libraries-bom 15.1.0
  docs/setup.md
Labels: automerge, cla: yes

#1183 build(java): use code-suggester v1 tag rather than full semver
  .github/workflows/formatting.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#1186 build(java): use actions/github-script v3 tag rather than full semver
  .github/workflows/approve-readme.yaml
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#1189 chore: libraries-bom 16.1.0
  docs/setup.md
Labels: automerge, cla: yes

#1190 chore(java): retry staging portion of the release with backoff
  .kokoro/common.sh
  .kokoro/release/stage.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#1191 build(java): enable blunderbuss for samples
  .github/blunderbuss.yml
  synth.metadata
Labels: automerge, cla: yes, context: full, samples
