Repository googleapis/google-http-java-client, pull requests merged in 2020-03, with the labels that each got.

#985 docs: libraries-bom 4.2.0
  docs/setup.md
Labels: cla: yes

#967 chore: update common templates
  .kokoro/linkage-monitor.sh
  synth.metadata
Labels: cla: yes

#989 chore: update common templates
  .kokoro/build.sh
  .kokoro/continuous/java8.cfg
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/java8.cfg
  .kokoro/nightly/samples.cfg
  .kokoro/presubmit/java8.cfg
  synth.metadata
Labels: cla: yes

#991 deps: httpclient 4.5.12
  pom.xml
Labels: cla: yes

#990 fix: Correctly handling chunked response streams with gzip
  google-http-client/src/main/java/com/google/api/client/http/HttpResponse.java
  google-http-client/src/test/java/com/google/api/client/http/HttpResponseTest.java
Labels: cla: yes

#1000 fix: add linkage monitor plugin
  pom.xml
Labels: cla: yes

#1002 fix: include request method and URL into HttpResponseException message
  google-http-client/src/main/java/com/google/api/client/http/HttpResponseException.java
  google-http-client/src/test/java/com/google/api/client/http/HttpResponseExceptionTest.java
Labels: cla: yes

#1007 docs: require Android 4.4
  README.md
Labels: cla: yes, priority: p2, semver: patch, type: docs

#1008 docs: android 4.4 or later is required
  docs/index.md
Labels: cla: yes

#1010 chore(doc): libraries-bom 4.3.0
  docs/setup.md
Labels: cla: yes, kokoro:run

#927 fix: incorrect check for Windows OS in FileDataStoreFactory
  google-http-client/src/main/java/com/google/api/client/util/store/FileDataStoreFactory.java
Labels: cla: yes
