Repository googleapis/google-http-java-client, pull requests merged in 2020-10, with the labels that each got.

#1127 docs: libaries-bom 11.0.0
  docs/setup.md
Labels: api: docs, cla: yes

#1136 docs: libraries-bom 12.0.0
  docs/setup.md
Labels: cla: yes

#1137 build(java): readme.sh should be executable
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#1046 fix: make google-http-client.properties file shading friendly
  google-http-client/src/main/java/com/google/api/client/http/HttpRequest.java
  google-http-client/src/main/resources/com/google/api/client/http/google-http-client.properties
Labels: cla: yes

#1143 ci(java): suggest formatting fixes
  .github/workflows/formatting.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#1148 ci(java): restrict presubmit samples ITs to only snapshot
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#1146 docs: libraries-bom 12.1.0
  docs/setup.md
Labels: api: docs, cla: yes

#1151 deps: guava 30.0-android
  pom.xml
Labels: cla: yes

#1161 chore: libraries-bom 13.3.0
  docs/setup.md
Labels: cla: yes

#1149 build(java): auto-approve README regeneration
  .github/workflows/approve-readme.yaml
  synth.metadata
Labels: cla: yes, context: full

#1162 [CHANGE ME] Re-generated to pick up changes from synthtool.
  .github/snippet-bot.yml
  .kokoro/build.sh
  .kokoro/release/publish_javadoc.sh
  CODE_OF_CONDUCT.md
  synth.metadata
Labels: cla: yes, context: full

#1164 chore(java): enable generated-files-bot
  .github/generated-files-bot.yml
  synth.metadata
Labels: automerge, cla: yes, context: full

#1147 feat: add mtls support for NetHttpTransport
  google-http-client/src/main/java/com/google/api/client/http/HttpTransport.java
  google-http-client/src/main/java/com/google/api/client/http/javanet/NetHttpTransport.java
  google-http-client/src/main/java/com/google/api/client/util/SecurityUtils.java
  google-http-client/src/main/java/com/google/api/client/util/SslUtils.java
  google-http-client/src/test/java/com/google/api/client/http/javanet/NetHttpTransportTest.java
  google-http-client/src/test/java/com/google/api/client/util/SecurityUtilsTest.java
  google-http-client/src/test/resources/com/google/api/client/util/cert.pem
  google-http-client/src/test/resources/com/google/api/client/util/mtlsCertAndKey.pem
  google-http-client/src/test/resources/com/google/api/client/util/privateKey.pem
Labels: cla: yes, do not merge

#1167 chore: add Beta annotation for new mtls functions
  google-http-client/src/main/java/com/google/api/client/http/HttpTransport.java
  google-http-client/src/main/java/com/google/api/client/http/javanet/NetHttpTransport.java
  google-http-client/src/main/java/com/google/api/client/util/SecurityUtils.java
  google-http-client/src/main/java/com/google/api/client/util/SslUtils.java
Labels: cla: yes
