Repository googleapis/google-http-java-client, pull requests merged in 2020-12, with the labels that each got.

#1195 chore(docs): add gradle instructions to setup.md
  docs/setup.md
Labels: api: docs, automerge, cla: yes

#1196 chore: Update publish_javadoc.sh
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#1202 ci(java): ignore bot users for generate-files-bot
  .github/generated-files-bot.yml
  synth.metadata
Labels: automerge, cla: yes, context: full

#1199 deps: update guava to 30.1-android
  pom.xml
Labels: cla: yes

#1203 docs: libraries-bom 16.2.0
  docs/setup.md
Labels: cla: yes

#1200 chore(deps): remove commons logging version
  pom.xml
Labels: cla: yes

#1210 chore: remove eclipse config
  samples/dailymotion-simple-cmdline-sample/.settings/org.eclipse.jdt.ui.prefs
  samples/dailymotion-simple-cmdline-sample/DailyMotionSample.launch
Labels: cla: yes

#1212 chore(java): remove formatter action
  .github/workflows/formatting.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full, merge
