Repository googleapis/google-http-java-client, pull requests merged in 2020-06, with the labels that each got.

#1006 fix: restore the thread's interrupted status after catching InterruptedException (#1005)
  google-http-client-apache-v2/src/main/java/com/google/api/client/http/apache/v2/ApacheHttpTransport.java
  google-http-client-apache-v2/src/main/java/com/google/api/client/http/apache/v2/ContentEntity.java
  google-http-client-apache-v2/src/main/java/com/google/api/client/http/apache/v2/package-info.java
  google-http-client-apache-v2/src/test/java/com/google/api/client/http/apache/v2/ApacheHttpTransportTest.java
  google-http-client-findbugs/src/main/java/com/google/api/client/findbugs/package-info.java
  google-http-client-gson/src/test/java/com/google/api/client/json/gson/GsonParserTest.java
  google-http-client-jackson2/src/main/java/com/google/api/client/json/jackson2/JacksonFactory.java
  google-http-client-jackson2/src/test/java/com/google/api/client/json/jackson2/JacksonParserTest.java
  google-http-client-test/src/main/java/com/google/api/client/test/json/AbstractJsonParserTest.java
  google-http-client-xml/src/main/java/com/google/api/client/xml/Xml.java
  google-http-client/src/main/java/com/google/api/client/http/HttpBackOffIOExceptionHandler.java
  google-http-client/src/main/java/com/google/api/client/http/HttpBackOffUnsuccessfulResponseHandler.java
  google-http-client/src/main/java/com/google/api/client/http/HttpIOExceptionHandler.java
  google-http-client/src/main/java/com/google/api/client/http/HttpRequest.java
  google-http-client/src/main/java/com/google/api/client/http/HttpResponse.java
  google-http-client/src/main/java/com/google/api/client/http/MultipartContent.java
  google-http-client/src/main/java/com/google/api/client/http/UriTemplate.java
  google-http-client/src/main/java/com/google/api/client/http/UrlEncodedParser.java
  google-http-client/src/main/java/com/google/api/client/http/apache/ApacheHttpTransport.java
  google-http-client/src/main/java/com/google/api/client/json/JsonString.java
  google-http-client/src/main/java/com/google/api/client/json/webtoken/DerEncoder.java
  google-http-client/src/main/java/com/google/api/client/json/webtoken/JsonWebSignature.java
  google-http-client/src/main/java/com/google/api/client/json/webtoken/JsonWebToken.java
  google-http-client/src/main/java/com/google/api/client/util/PemReader.java
  google-http-client/src/main/java/com/google/api/client/util/escape/CharEscapers.java
  google-http-client/src/main/java/com/google/api/client/util/escape/PercentEscaper.java
  google-http-client/src/main/java/com/google/api/client/util/store/FileDataStoreFactory.java
  google-http-client/src/test/java/com/google/api/client/http/ConsumingInputStreamTest.java
  google-http-client/src/test/java/com/google/api/client/http/HttpBackOffIOExpcetionHandlerTest.java
  google-http-client/src/test/java/com/google/api/client/http/HttpBackOffUnsuccessfulResponseHandlerTest.java
  google-http-client/src/test/java/com/google/api/client/http/HttpRequestTest.java
  google-http-client/src/test/java/com/google/api/client/http/HttpRequestTracingTest.java
  google-http-client/src/test/java/com/google/api/client/http/HttpResponseTest.java
  google-http-client/src/test/java/com/google/api/client/http/MultipartContentTest.java
  google-http-client/src/test/java/com/google/api/client/http/OpenCensusUtilsTest.java
  google-http-client/src/test/java/com/google/api/client/json/webtoken/JsonWebSignatureTest.java
  google-http-client/src/test/java/com/google/api/client/util/DateTimeTest.java
  google-http-client/src/test/java/com/google/api/client/util/GenericDataTest.java
  google-http-client/src/test/java/com/google/api/client/util/IOUtilsTest.java
  google-http-client/src/test/java/com/google/api/client/util/escape/PercentEscaperTest.java
Labels: cla: yes

#1058 ci: lock google-java-formatter version
  google-http-client-bom/pom.xml
  pom.xml
Labels: automerge, cla: yes

#1043 chore: update common templates
  .github/workflows/ci.yaml
  .kokoro/build.bat
  synth.metadata
Labels: automerge, cla: yes, context: full

#1056 chore(docs): libraries-bom 7.0.0
  docs/setup.md
Labels: cla: yes

#1066 chore(docs): libraries-bom 8.0.0
  docs/setup.md
Labels: cla: yes

#1067 chore: regenerate common templates
  .github/CODEOWNERS
  .github/workflows/ci.yaml
  .kokoro/build.sh
  .kokoro/dependencies.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/integration.cfg
  .kokoro/presubmit/samples.cfg
  .kokoro/trampoline.sh
  .repo-metadata.json
  CONTRIBUTING.md
  synth.metadata
  synth.py
Labels: cla: yes

#1069 samples: replace Google+ json example with YouTube example
  docs/json.md
  samples/snippets/pom.xml
  samples/snippets/src/main/java/com/example/json/YouTubeSample.java
  samples/snippets/src/main/resources/youtube-search.json
  samples/snippets/src/test/java/com/example/json/YouTubeSampleTest.java
Labels: cla: yes

#1070 feat: add Android 19 compatible FileDataStoreFactory implementation
  google-http-client-android/src/main/java/com/google/api/client/extensions/android/util/store/FileDataStoreFactory.java
  google-http-client/pom.xml
  google-http-client/src/main/java/com/google/api/client/util/store/FileDataStoreFactory.java
  pom.xml
Labels: cla: yes
