Repository googleapis/google-http-java-client, pull requests merged in 2021-09, with the labels that each got.

#1451 chore: remove readme autosynth config
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
Labels: kokoro:force-run, cla: yes, automerge

#1452 chore: re-generated to pick up changes from self
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
  synth.metadata
Labels: cla: yes, context: none

#1453 chore: update java docfx doclet
  pom.xml
Labels: cla: yes

#1449 chore: update common templates
  .github/release-trigger.yml
  .github/workflows/ci.yaml
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  renovate.json
  synth.metadata
Labels: cla: yes, context: full, automerege

#1455 chore: remove units(7) and linkage monitor from required checks
  .github/sync-repo-settings.yaml
Labels: cla: yes, automerge

#1456 chore: add gcf-owl-bot to list of trusted contributors
  .github/readme/synth.py
  .github/trusted-contribution.yml
  .kokoro/continuous/readme.cfg
  .kokoro/release/common.sh
  .kokoro/release/drop.sh
  .kokoro/release/promote.sh
  .kokoro/release/publish_javadoc.sh
  .kokoro/release/publish_javadoc11.sh
  .kokoro/release/stage.sh
  .kokoro/trampoline.sh
  synth.metadata
Labels: cla: yes, context: full

#1459 chore(java): remove dependencyDashboardLabel config from renovate.json
  renovate.json
  synth.metadata
Labels: cla: yes, context: full

#1457 chore: update java-docfx-doclet version
  pom.xml
Labels: cla: yes

#1463 chore: change branch master to main in sync-repo-settings.yaml
  .github/sync-repo-settings.yaml
Labels: cla: yes, automerge

#1465 chore: change branch master to main in github configurations
  .github/blunderbuss.yml
  .github/workflows/ci.yaml
Labels: cla: yes, automerge
