Repository googleapis/google-http-java-client, pull requests merged in 2021-06, with the labels that each got.

#1382 chore: dump maven version along with java
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#1381 chore: add cloud-rad doc generation
  pom.xml
Labels: cla: yes, kokoro:force-run

#1400 docs: com.google.cloud:libraries-bom:20.7.0
  docs/setup.md
Labels: cla: yes
