Repository googleapis/google-http-java-client, pull requests merged in 2021-02, with the labels that each got.

#1242 deps: update OpenCensus for consistency with gRPC
  pom.xml
Labels: cla: yes

#1250 docs: libraries-bom 16.4.0
  docs/setup.md
Labels: cla: yes

#1266 build: no one pays attention to this
  .github/workflows/samples.yaml
  synth.metadata
Labels: automerge, cla: yes

#1265 docs: jackson does not maintain stable Javadocs
  google-http-client-jackson2/pom.xml
  pom.xml
Labels: cla: yes

#1268 deps: version manage error_prone_annotations to 2.5.1
  pom.xml
Labels: cla: yes

#1275 fix: remove old broken link
  google-http-client-jackson2/src/main/java/com/google/api/client/json/jackson2/package-info.java
Labels: automerge, cla: yes

#1273 ci: removing Kokoro settings that are covered by GitHub Actions
  .github/sync-repo-settings.yaml
Labels: cla: yes

#1243 fix: refactor to use StandardCharsets
  google-http-client/src/main/java/com/google/api/client/http/AbstractHttpContent.java
  google-http-client/src/main/java/com/google/api/client/http/HttpResponse.java
  google-http-client/src/main/java/com/google/api/client/http/UrlEncodedParser.java
  google-http-client/src/main/java/com/google/api/client/json/JsonFactory.java
  google-http-client/src/main/java/com/google/api/client/testing/http/MockLowLevelHttpRequest.java
  google-http-client/src/test/java/com/google/api/client/http/MultipartContentTest.java
Labels: automerge, cla: yes

#1280 build: stop generating samples ci. update templated renovate
  .github/workflows/samples.yaml
  renovate.json
  synth.py
Labels: automerge, cla: yes, samples

#1292 chore(deps): libraries BOM 17.0.0
  docs/setup.md
Labels: cla: yes

#1255 fix: fix buildRequest setUrl order
  google-http-client/src/main/java/com/google/api/client/http/HttpRequestFactory.java
  google-http-client/src/test/java/com/google/api/client/http/HttpRequestFactoryTest.java
Labels: cla: yes

#1299 chore(deps): libraries-bom 18.0.0
  docs/setup.md
Labels: cla: yes

#1296 docs: update version
  google-http-client-bom/README.md
Labels: cla: yes
