Repository googleapis/google-http-java-client, pull requests merged in 2021-04, with the labels that each got.

#1333 deps: update Guava patch
  pom.xml
Labels: cla: yes

#1336 build(java): skip javadoc tests during dependencies test
  .kokoro/dependencies.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#1342 fix: typo
  .kokoro/build.sh
  synth.metadata
Labels: cla: yes, context: full

#1341 fix: update protoc plugin
  google-http-client-protobuf/pom.xml
  pom.xml
Labels: cla: yes

#1344 fix: release scripts from issuing overlapping phases
  .kokoro/release/snapshot.sh
  .kokoro/release/stage.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#1347 docs: libraries-bom 20.1.0
  docs/setup.md
Labels: cla: yes

#1345 fix: test error responses such as 403
  google-http-client-apache-v2/src/test/java/com/google/api/client/http/apache/v2/ApacheHttpTransportTest.java
  google-http-client/src/main/java/com/google/api/client/http/HttpResponse.java
Labels: cla: yes
