Repository googleapis/google-http-java-client, pull requests merged in 2021-03, with the labels that each got.

#1297 chore: fix build warnings
  samples/snippets/pom.xml
  samples/snippets/src/main/java/com/example/json/YouTubeSample.java
  samples/snippets/src/test/java/com/example/json/YouTubeSampleTest.java
Labels: cla: yes

#1306 chore: remove docLava v2 doc generation
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#1305 fix: default application/json charset to utf-8
  google-http-client/src/main/java/com/google/api/client/http/HttpResponse.java
  google-http-client/src/test/java/com/google/api/client/http/HttpResponseTest.java
Labels: automerge, cla: yes

#1307 chore: update README with CI, stability, latest version badges
  README.md
Labels: cla: yes

#1312 docs: 19.0.0 libraries-bom
  docs/setup.md
Labels: cla: yes

#1313 chore: copy README to docfx-yml dir
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#1314 build(java): update autorelease title check in response to the new multi release branch changes
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#1315 fix: when disconnecting, close the underlying connection before the response InputStream
  google-http-client-apache-v2/src/test/java/com/google/api/client/http/apache/v2/ApacheHttpTransportTest.java
  google-http-client/src/main/java/com/google/api/client/http/HttpResponse.java
  google-http-client/src/test/java/com/google/api/client/http/javanet/NetHttpTransportTest.java
Labels: automerge, cla: yes

#1319 chore(deps): libraries BOM 19.1.0
  docs/setup.md
Labels: cla: yes

#1322 chore(deps): libraries-bom 19.2.1
  docs/setup.md
Labels: cla: yes

#1324 chore(java): detect sample-secrets in build.sh
  .kokoro/build.sh
  synth.metadata
Labels: automerge, build.sh, cla: yes, context: full, in, sample-secrets, samples

#1326 chore: remove staging bucket v2
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: automerge, cla: yes, context: full
