Repository googleapis/google-http-java-client, pull requests merged in 2021-05, with the labels that each got.

#1357 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: automerge, cla: yes, context: none

#1359 build: configure branch 1.39.2-sp as a release branch
  .github/release-please.yml
  .github/sync-repo-settings.yaml
Labels: automerge, cla: yes

#1354 chore(docs): libraries-bom 20.2.0
  docs/setup.md
Labels: cla: yes

#1360 feat: configure initial sp version
  .github/workflows/ci.yaml
  google-http-client-protobuf/pom.xml
  pom.xml
Labels: cla: yes

#1365 chore: adding cloud-rad java xrefs
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#1368 docs: bom 20.3.0
  docs/setup.md
Labels: cla: yes

#1370 test: relax test to allow sp versions
  google-http-client/src/test/java/com/google/api/client/http/HttpRequestTest.java
Labels: automerge, cla: yes

#1374 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#1379 chore: add changelog to cloud-rad
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#1380 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  .github/generated-files-bot.yml
  synth.metadata
Labels: automerge, cla: yes, context: full

#1389 build: switch all clients to use the google endpoint on sonatype
  pom.xml
Labels: automerge, cla: yes
