Repository googleapis/google-http-java-client, pull requests merged in 2021-01, with the labels that each got.

#1218 chore(deps): libraries BOM 16.2.1
  docs/setup.md
Labels: cla: yes

#1220 fix: JSON spec mandates UTF-8
  google-http-client-gson/src/main/java/com/google/api/client/json/gson/GsonFactory.java
Labels: cla: yes

#1216 fix: deprecate JacksonFactory to align with security team advice
  google-http-client-jackson2/src/main/java/com/google/api/client/json/jackson2/JacksonFactory.java
  google-http-client-jackson2/src/main/java/com/google/api/client/json/jackson2/JacksonGenerator.java
  google-http-client-jackson2/src/main/java/com/google/api/client/json/jackson2/JacksonParser.java
Labels: cla: yes

#1215 fix: fix some deprecation warnings in Java 9+
  google-http-client-xml/src/main/java/com/google/api/client/xml/Xml.java
  google-http-client/src/main/java/com/google/api/client/util/Data.java
  google-http-client/src/test/java/com/google/api/client/util/ObjectsTest.java
Labels: cla: yes

#1227 chore(deps): libraries-bom 16.3.0
  docs/setup.md
Labels: cla: yes

#986 add http.status_code attribute to all Spans that have a lowLevelHttpResponse
  google-http-client/src/main/java/com/google/api/client/http/HttpRequest.java
  google-http-client/src/test/java/com/google/api/client/http/HttpRequestTracingTest.java
Labels: cla: yes

#1228 unused logger
  google-http-client/src/main/java/com/google/api/client/util/store/FileDataStoreFactory.java
Labels: cla: yes

#1231 chore: deprecate obsolete utility methods
  google-http-client/src/main/java/com/google/api/client/http/HttpRequest.java
  google-http-client/src/main/java/com/google/api/client/util/Base64.java
  google-http-client/src/main/java/com/google/api/client/util/Beta.java
  google-http-client/src/main/java/com/google/api/client/util/ByteArrayStreamingContent.java
  google-http-client/src/main/java/com/google/api/client/util/ByteStreams.java
  google-http-client/src/main/java/com/google/api/client/util/Charsets.java
  google-http-client/src/main/java/com/google/api/client/util/Collections2.java
  google-http-client/src/main/java/com/google/api/client/util/IOUtils.java
  google-http-client/src/main/java/com/google/api/client/util/StreamingContent.java
Labels: cla: yes

#1233 chore: adding docfx doclet resource
  .kokoro/release/publish_javadoc.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full

#1234 build: migrate to flakybot
  .kokoro/build.sh
Labels: automerge, cla: yes
