Repository googleapis/google-http-java-client, pull requests merged in 2022-04, with the labels that each got.

#1626 deps: revert dependency com.google.protobuf:protobuf-java to v3.19.4
  pom.xml
Labels: automerge, size: xs

#1633 feat: next release from main branch is 1.42.0
  .github/release-please.yml
  .github/sync-repo-settings.yaml
Labels: automerge, size: s

#1634 ci: configure the protected branch
  .github/workflows/ci.yaml
  .github/workflows/downstream.yaml
Labels: automerge, size: l

#1645 deps: downgrade appengine to 1.9.X
  pom.xml
Labels: size: xs
