Repository googleapis/google-http-java-client, pull requests merged in 2023-11, with the labels that each got.

#1896 build: add native image kokoro cfgs
  .kokoro/build.sh
  .kokoro/presubmit/graalvm-native-a.cfg
  .kokoro/presubmit/graalvm-native-b.cfg
  owlbot.py
Labels: size: m

#1893 fix: native image configs for google-http-java-client
  .kokoro/build.sh
  .kokoro/presubmit/graalvm-native-a.cfg
  google-http-client-apache-v2/src/main/resources/META-INF/native-image/com.google.http-client/google-http-client-apache-v2/reflect-config.json
  google-http-client-gson/src/main/resources/META-INF/native-image/com.google.http-client/google-http-client-gson/reflect-config.json
  google-http-client-jackson2/src/main/resources/META-INF/native-image/com.google.http-client/google-http-client-jackson2/reflect-config.json
  google-http-client-jackson2/src/test/resources/META-INF/native-image/com.google.http-client/google-http-client-jackson2/native-image.properties
  google-http-client-protobuf/src/main/resources/META-INF/native-image/com.google.http-client/google-http-client-protobuf/reflect-config.json
  google-http-client-test/pom.xml
  google-http-client-test/src/main/resources/META-INF/native-image/com.google.http-client/google-http-client-test/reflect-config.json
  google-http-client-test/src/main/resources/META-INF/native-image/com.google.http-client/google-http-client-test/serialization-config.json
  google-http-client-xml/src/main/resources/META-INF/native-image/com.google.http-client/google-http-client-xml/reflect-config.json
  google-http-client-xml/src/test/resources/META-INF/native-image/com.google.http-client/google-http-client-xml/reflect-config.json
  google-http-client-xml/src/test/resources/META-INF/native-image/com.google.http-client/google-http-client-xml/resource-config.json
  google-http-client/src/main/resources/META-INF/native-image/com.google.http-client/google-http-client/native-image.properties
  google-http-client/src/main/resources/META-INF/native-image/com.google.http-client/google-http-client/reflect-config.json
  google-http-client/src/main/resources/META-INF/native-image/com.google.http-client/google-http-client/resource-config.json
  google-http-client/src/main/resources/META-INF/native-image/com.google.http-client/google-http-client/serialization-config.json
  google-http-client/src/test/resources/META-INF/native-image/com.google.http-client/google-http-client/native-image.properties
  google-http-client/src/test/resources/META-INF/native-image/com.google.http-client/google-http-client/reflect-config.json
  google-http-client/src/test/resources/META-INF/native-image/com.google.http-client/google-http-client/resource-config.json
  pom.xml
Labels: size: xl

#1901 feat: add isShutdown in HttpTransport
  google-http-client/src/main/java/com/google/api/client/http/HttpTransport.java
Labels: size: s
