Repository googleapis/google-http-java-client, pull requests merged in 2024-07, with the labels that each got.

#1961 deps: update dependency com.google.cloud:native-image-shared-config to v1.9.0
  .kokoro/presubmit/graalvm-native-a.cfg
  .kokoro/presubmit/graalvm-native-b.cfg
  pom.xml
Labels: size: xs

#1962 chore: Use renovate's suggested config
  renovate.json
Labels: kokoro:force-run, automerge, size: s

#1963 chore: fix renovate bot settings for native-image-shared-config pom update
  renovate.json
Labels: size: xs

#1968 chore: Limit guava version to v30
  renovate.json
Labels: kokoro:force-run, size: xs

#1969 Revert "chore: Limit guava version to v30"
  renovate.json
Labels: size: xs
