Repository googleapis/google-http-java-client, pull requests merged in 2024-01, with the labels that each got.

#1905 deps: testing exlcusing commons-logging
  google-http-client/pom.xml
Labels: size: xs

#1916 deps: newer grpc-context to override old one
  google-http-client/pom.xml
  pom.xml
Labels: size: s

#1883 fix: serialVersionUID fix for Serializable Classes
  google-http-client/src/main/java/com/google/api/client/util/DateTime.java
Labels: size: xs

#1922 chore: fix declaration of maven-source-plugin for v3.3.0
  google-http-client-android/pom.xml
  google-http-client-apache-v2/pom.xml
  google-http-client-appengine/pom.xml
  google-http-client-findbugs/pom.xml
  google-http-client-gson/pom.xml
  google-http-client-jackson2/pom.xml
  google-http-client-protobuf/pom.xml
  google-http-client-test/pom.xml
  google-http-client-xml/pom.xml
  google-http-client/pom.xml
  pom.xml
Labels: size: m
