Repository googleapis/google-http-java-client, pull requests merged in 2024-08, with the labels that each got.

#1972 feat: next release from main is 1.45.0
  .github/release-please.yml
  .github/sync-repo-settings.yaml
Labels: size: s

#1960 feat: Introduce google-http-client-apache-v5 (Apache Client/Core 5.x)
  .github/workflows/ci-java7.yaml
  docs/http-transport.md
  google-http-client-apache-v5/pom.xml
  google-http-client-apache-v5/src/main/java/com/google/api/client/http/apache/v5/Apache5ContentEntity.java
  google-http-client-apache-v5/src/main/java/com/google/api/client/http/apache/v5/Apache5HttpRequest.java
  google-http-client-apache-v5/src/main/java/com/google/api/client/http/apache/v5/Apache5HttpResponse.java
  google-http-client-apache-v5/src/main/java/com/google/api/client/http/apache/v5/Apache5HttpTransport.java
  google-http-client-apache-v5/src/main/java/com/google/api/client/http/apache/v5/Apache5ResponseContent.java
  google-http-client-apache-v5/src/main/java/com/google/api/client/http/apache/v5/package-info.java
  google-http-client-apache-v5/src/test/java/com/google/api/client/http/apache/v5/Apache5HttpRequestTest.java
  google-http-client-apache-v5/src/test/java/com/google/api/client/http/apache/v5/Apache5HttpTransportTest.java
  google-http-client-apache-v5/src/test/java/com/google/api/client/http/apache/v5/MockClassicHttpResponse.java
  google-http-client-apache-v5/src/test/java/com/google/api/client/http/apache/v5/MockHttpClient.java
  google-http-client-assembly/classpath-include
  google-http-client-assembly/readme.html
  pom.xml
  versions.txt
Labels: automerge, size: xl

#2010 chore: remove owlbot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  .github/generated-files-bot.yml
  codecov.yaml
  owlbot.py
  synth.metadata
Labels: size: m
