Repository googleapis/google-http-java-client, pull requests merged in 2025-02, with the labels that each got.

#2071 fix: remove unnecessary nexus plugin activation
  google-http-client-appengine/pom.xml
  google-http-client-bom/pom.xml
  google-http-client-findbugs/pom.xml
  pom.xml
  samples/dailymotion-simple-cmdline-sample/pom.xml
  samples/pom.xml
Labels: size: l

#2072 Revert "deps: update dependency io.grpc:grpc-context to v1.70.0"
  pom.xml
Labels: size: xs

#2074 chore: freeze guava and grpc dependencies until after LTS 8 is released
  renovate.json
Labels: size: s

#2078 deps: update grpc-context to 1.70.0
  pom.xml
Labels: kokoro:force-run, size: xs

#2082 chore: update native-image-shared-config
  pom.xml
Labels: size: xs

#2087 feat: next release from main branch is 1.47.0
  .github/release-please.yml
  .github/sync-repo-settings.yaml
Labels: size: s
